### ISSUE TITLE
Error on link to the map tweet

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/cognicity-reports#15]
Hi all cc @talltom @matthewberryman @asbarve @ojha-url ,

I did a test report this morning through Twitter. The report was successfully uploaded (including the image), however, the notification tweet that usually says "I put your report on the map [map link]" is now says "undefined":

![20171122 1](https://user-images.githubusercontent.com/22338984/33109631-533ee64a-cf75-11e7-9145-f048889b877a.PNG)

screenshot of successful report below:
![2017 11 22 2](https://user-images.githubusercontent.com/22338984/33109641-63f39030-cf75-11e7-8771-8f5ac1ed91db.PNG)

**Comment by tomasholderness** [comment]
Related https://github.com/urbanriskmap/cognicity-reports-powertrack/issues/27

**Comment by tomasholderness** [comment]
Hi @prittandrani this is now fixed. It occurs because Twitter uses the code 'in' to refer to the Indonesian language and not 'id' as per ISO 639 (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). This fix got left out of a recent update.

Thank you for the report!
